config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :proponents
  devise_for :users
  get 'report', to: "dashboard#report"
  root 'dashboard#index'

  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/proponent.rb
class Proponent < ApplicationRecord
  validates :name, :document, :born_in,
            :street, :district, :city, :state,
            :cep, :phone, :salary, :discount, presence: true


  def salary_range
    case salary
    when 0..1045
      'Até R$ 1.045,00'
    when 1045.01..2089.60
      'De R$ 1.045,01 a R$ 2.089,60'
    when 2089.61..3134.40
      'De R$ 2.089,61 até R$ 3.134,40'
    when 3134.40..6101.06
      'De R$ 3.134,41 até R$ 6.101,06'
    else
      'Acima de R$ 6.101,07'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  def index; end

  def report
    @proponents = Proponent.all.group_by(&:salary_range)
  end
end

app/controllers/proponents_controller.rb
class ProponentsController < ApplicationController
  include ActionView::Helpers::NumberHelper
  before_action :set_proponent, only: %i[ show edit update destroy ]

  # GET /proponents or /proponents.json
  def index
    @proponents = Proponent.page(params[:page] || 1)
  end

  # GET /proponents/1 or /proponents/1.json
  def show
  end

  # GET /proponents/new
  def new
    @proponent = Proponent.new
  end

  # GET /proponents/1/edit
  def edit
    @proponent.salary =  number_to_currency(@proponent.salary, unit: "R$ ", separator: ",", delimiter: ".")
  end

  # POST /proponents or /proponents.json
  def create
    @proponent = Proponent.new(proponent_params)

    respond_to do |format|
      if @proponent.save
        format.html { redirect_to proponents_url, notice: "Proponent was successfully created." }
        format.json { render :show, status: :created, location: @proponent }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @proponent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proponents/1 or /proponents/1.json
  def update
    respond_to do |format|
      if @proponent.update(proponent_params)
        format.html { redirect_to proponents_url, notice: "Proponent was successfully updated." }
        format.json { render :show, status: :ok, location: @proponent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @proponent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proponents/1 or /proponents/1.json
  def destroy
    @proponent.destroy!

    respond_to do |format|
      format.html { redirect_to proponents_url, notice: "Proponent was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proponent
      @proponent = Proponent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def proponent_params
      params.require(:proponent).permit(:name, :document, :born_in, :street, :number, :district, :city, :state, :cep, :phone, :phone2, :salary, :discount)
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/dashboard_helper.rb
# frozen_string_literal: true

module DashboardHelper
end

app/helpers/proponents_helper.rb
module ProponentsHelper
end

app/views/dashboard/index.html.erb
<div class="p-5">
  <h1>Bem-vindo</h1>
</div>

app/views/dashboard/report.html.erb
<% labels = [] %>
<% qtd = [] %>
<div class="d-flex justify-content-center align-items-center bg-body-secondary">
  <div class="card centered w-50 borderless my-5">
    <div class="card-header d-flex justify-content-between">
      <h3>Relatório</h3>
    </div>

    <% @proponents.each do |range, proponents| %>
      <% labels << range %>
      <% qtd << proponents.count %>
      <h3 class="m-3">Faixa: <%= range %></h3>

      <table class="table">
        <thead>
        <tr>
          <th scope="col">Nome</th>
          <th scope="col">Salário</th>
        </tr>
        </thead>
        <tbody>
        <% proponents.each do |proponent| %>
          <tr>
            <td><%= proponent.name %></td>
            <td><%= number_to_currency(proponent.salary, unit: "R$", separator: ",", delimiter: ".") %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>
</div>

<div class="d-flex justify-content-center align-items-center bg-body-secondary">
  <div class="card centered w-50 borderless my-5">
    <div class="card-header d-flex justify-content-between">
      <h3>Gráfico Quantitativo</h3>
    </div>
    <canvas
      data-controller="hello"
      data-target="hello.chart"
      data-hello-labels-value="<%=labels %>"
      data-hello-qtd-value="<%=qtd %>"
    ></canvas>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DescontoInss</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  </head>

  <body>
  <% if current_user %>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Desconto INSS</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <%= link_to "Home", root_path, class: "nav-link" %>
            <%= link_to "Propoente", proponents_path, class: "nav-link" %>
            <%= link_to "Relátorios", report_path, class: "nav-link" %>
          </div>
        </div>
      </div>
    </nav>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/proponents/_form.html.erb
<div data-controller="address">
  <%= form_with(model: proponent) do |form| %>
    <% if proponent.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(proponent.errors.count, "error") %> prohibited this proponent from being saved:</h2>

        <ul>
          <% proponent.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="row py-2">
      <div class="col-6">
        <%= form.label :name %>
        <%= form.text_field :name, placeholder: "Nome Completo", class: "form-control" %>
      </div>

      <div class="col-4">
        <%= form.label :document, style: "display: block" %>
        <%= form.text_field :document, placeholder: "CPF", class: "form-control", data: { controller: "cpf", "cpf-target": "input" } %>
      </div>

      <div class="col-2">
        <%= form.label :born_in, style: "display: block" %>
        <%= form.date_field :born_in, class: "form-control" %>
      </div>
    </div>
    <fieldset class="border rounded p-4 my-3">
      <legend>Endereço</legend>
      <div class="row py-2">
        <div class="col-3">
          <%= form.label :cep, style: "display: block" %>
          <%= form.text_field :cep, class: "form-control", data: { controller: "cep", "cep-target": "input", action: "blur->address#get" } %>
        </div>
        <div class="col-9">
          <%= form.label :street, style: "display: block" %>
          <%= form.text_field :street, class: "form-control", data: {  "address-target": "street"} %>
        </div>

      </div>

      <div class="row py-2">
        <div class="col-2">
          <%= form.label :number, style: "display: block" %>
          <%= form.number_field :number, class: "form-control" %>
        </div>
        <div class="col-4">
          <%= form.label :district, style: "display: block" %>
          <%= form.text_field :district, class: "form-control", data: {  "address-target": "district"} %>
        </div>

        <div class="col-3">
          <%= form.label :city, style: "display: block" %>
          <%= form.text_field :city, class: "form-control", data: {  "address-target": "city"} %>
        </div>

        <div class="col-3">
          <%= form.label :state, style: "display: block" %>
          <%= form.text_field :state, class: "form-control",  data: {  "address-target": "state"} %>
        </div>
      </div>

    </fieldset>


    <fieldset class="border rounded p-4 my-3">
      <legend>Contato</legend>

      <div class="row py-2">
        <div class="col-6">
          <%= form.label :phone, style: "display: block" %>
          <%= form.text_field :phone, class: "form-control", data: { controller: "phone", "phone-target": "input"} %>
        </div>

        <div class="col-6">
          <%= form.label :phone2, style: "display: block" %>
          <%= form.text_field :phone2, class: "form-control", data: { controller: "phone", "phone-target": "input"} %>
        </div>
      </div>
    </fieldset>


    <legend>Salário</legend>
    <div class="row py-2" data-controller="calc">
      <div class="col-3">
        <%= form.label :salary, style: "display: block" %>
        <%= form.text_field :salary, class: "form-control", data: { controller: "currency", "currency-target": "input", action: "blur->calc#get"} %>
      </div>
      <div class="col-3">
        <strong data-calc-target="discount" class="d-flex justify-content-center align-items-center bg-body-secondary mt-4 p-2">
          Descontos: <%=@proponent.discount %>
        </strong>
      </div>
      <div class="col-3">
        <%= form.hidden_field :discount, data: { "calc-target": "input" } %>
      </div>
    </div>

    <hr/>
    <div class="d-grid gap-2 col-6 mx-auto">
      <%= form.submit "Savar Propoente", class: "btn btn-primary" %>
    </div>
  <% end %>

</div>

app/views/proponents/_proponent.html.erb
<tr id="<%= dom_id proponent %>">
  <th scope="row">
    <%= link_to  edit_proponent_path(proponent) do  %>
      <svg
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          fill-rule="evenodd"
          clip-rule="evenodd"
          d="M21.2635 2.29289C20.873 1.90237 20.2398 1.90237 19.8493 2.29289L18.9769 3.16525C17.8618 2.63254 16.4857 2.82801 15.5621 3.75165L4.95549 14.3582L10.6123 20.0151L21.2189 9.4085C22.1426 8.48486 22.338 7.1088 21.8053 5.99367L22.6777 5.12132C23.0682 4.7308 23.0682 4.09763 22.6777 3.70711L21.2635 2.29289ZM16.9955 10.8035L10.6123 17.1867L7.78392 14.3582L14.1671 7.9751L16.9955 10.8035ZM18.8138 8.98525L19.8047 7.99429C20.1953 7.60376 20.1953 6.9706 19.8047 6.58007L18.3905 5.16586C18 4.77534 17.3668 4.77534 16.9763 5.16586L15.9853 6.15683L18.8138 8.98525Z"
          fill="currentColor"
          />
        <path
          d="M2 22.9502L4.12171 15.1717L9.77817 20.8289L2 22.9502Z"
          fill="currentColor"
          />
      </svg>
    <% end %>
  </th>
  <td><%= proponent.name %></td>
  <td><%= number_to_currency(proponent.salary, unit: "R$", separator: ",", delimiter: ".") %></td>
  <td><%= number_to_currency(proponent.discount, unit: "R$", separator: ",", delimiter: ".") %></td>
</tr>

app/views/proponents/edit.html.erb
<div class="d-flex justify-content-center align-items-center vh-100 bg-body-secondary">

  <div class="card centered w-50 borderless">
    <div class="card-header d-flex justify-content-between">
      <h3>Editar Propoente <%=@proponent.name %></h3>
      <%= link_to  proponents_path, class: "btn" do  %>
        <svg
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M17.7427 8.46448L19.1569 9.87869L17.0356 12L19.157 14.1214L17.7428 15.5356L15.6214 13.4142L13.5 15.5355L12.0858 14.1213L14.2072 12L12.0859 9.87878L13.5002 8.46457L15.6214 10.5858L17.7427 8.46448Z"
            fill="currentColor"
            />
          <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M8.58579 19L2.29289 12.7071C1.90237 12.3166 1.90237 11.6834 2.29289 11.2929L8.58579 5H22.5857V19H8.58579ZM9.41421 7L4.41421 12L9.41421 17H20.5857V7H9.41421Z"
            fill="currentColor"
            />
        </svg>
        Voltar
      <% end %>
    </div>
    <div class="card-body">
      <%= render "form", proponent: @proponent %>
    </div>
  </div>
</div>

app/views/proponents/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="d-flex justify-content-center align-items-center vh-100  bg-body-secondary">

  <div class="card centered w-50 borderless">
    <div class="card-header d-flex justify-content-between">
      <h3>Lista Propoentes </h3>
      <%= link_to "Novo(a) Propoente", new_proponent_path %>
    </div>

    <table class="table">
      <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nome</th>
        <th scope="col">Salário</th>
        <th scope="col">Desconto</th>
      </tr>
      </thead>
      <tbody>
      <% @proponents.each do |proponent| %>
        <%= render proponent %>
        <% end %>
      </tbody>
    </table>

    <div class="d-flex justify-content-center">
      <%= paginate @proponents, theme: 'bootstrap-5' %>
    </div>
  </div>
</div>

app/views/proponents/new.html.erb
<div class="d-flex justify-content-center align-items-center vh-100 bg-body-secondary">

  <div class="card centered w-50 borderless">
    <div class="card-header d-flex justify-content-between">
      <h3>Novo Propoente</h3>
      <%= link_to  proponents_path, class: "btn" do  %>
        <svg
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
        >
          <path
            d="M17.7427 8.46448L19.1569 9.87869L17.0356 12L19.157 14.1214L17.7428 15.5356L15.6214 13.4142L13.5 15.5355L12.0858 14.1213L14.2072 12L12.0859 9.87878L13.5002 8.46457L15.6214 10.5858L17.7427 8.46448Z"
            fill="currentColor"
            />
          <path
            fill-rule="evenodd"
            clip-rule="evenodd"
            d="M8.58579 19L2.29289 12.7071C1.90237 12.3166 1.90237 11.6834 2.29289 11.2929L8.58579 5H22.5857V19H8.58579ZM9.41421 7L4.41421 12L9.41421 17H20.5857V7H9.41421Z"
            fill="currentColor"
            />
        </svg>
        Voltar
      <% end %>
    </div>
    <div class="card-body">
      <%= render "form", proponent: @proponent %>
    </div>
  </div>
</div>

app/views/proponents/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @proponent %>

<div>
  <%= link_to "Edit this proponent", edit_proponent_path(@proponent) %> |
  <%= link_to "Back to proponents", proponents_path %>

  <%= button_to "Destroy this proponent", @proponent, method: :delete %>
</div>